@echo off
cd ..
echo RUN clean  ...
call mvn -B -V -e clean > .\prod\package_SNAPSHOT_with_DEPLOY.log
echo End clean

echo RUN package ...
call mvn package -B -V -e >> .\prod\package_SNAPSHOT_with_DEPLOY.log
echo End package ...

echo RUN deploy ...
call mvn deploy -B -V -e -Dmaven.test.skip=true >> .\prod\package_SNAPSHOT_with_DEPLOY.log
echo End deploy ...
pause
